"""added restaurant

Revision ID: a21b03985e9b
Revises: e579e056e555
Create Date: 2023-09-26 13:09:47.316348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21b03985e9b'
down_revision = 'e579e056e555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
