"""added restaurant

Revision ID: cca375a2815a
Revises: a21b03985e9b
Create Date: 2023-09-26 21:57:24.039458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca375a2815a'
down_revision = 'a21b03985e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
